name: flutter_sample
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <=3.3.3"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_crashlytics: ^2.8.8
  firebase_analytics: ^9.3.2
  firebase_core: ^1.21.0

  flutter_localizations: # Add this line
    sdk: flutter
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  http: ^0.13.5
  path_provider: ^2.0.11
  flutter_screenutil: ^5.5.4
  location: ^4.4.0
  geocoding: ^2.0.5
  google_maps_flutter: ^2.2.1
  flutter_polyline_points: ^1.0.0
  flutter_chat_ui: ^1.6.5
  flutter_chat_types: ^3.5.0
  file_picker: ^5.2.1
  mime: ^1.0.2
  intl: ^0.17.0
  cloud_firestore: ^3.4.9
  firebase_messaging: ^13.0.3
  flutter_local_notifications: ^11.0.1
  event_bus: ^2.0.0
  google_sign_in: ^5.4.2
  firebase_auth: ^3.10.0
  flutter_facebook_auth: ^4.4.1
  sqflite: ^2.0.3+1
  video_player: ^2.4.7
  google_mobile_ads: ^2.0.1
  firebase_remote_config: ^2.0.19
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

 # fonts:
 #   - family: Lato
  #    - asset: fonts/Lato-Bold.ttf
   #     - asset: fonts/Lato-Italic.ttf

